In [1]:
# Sếp đưa cho bạn dữ liệu doanh số của 4 nhân viên trong Quý 1 (Tháng 1, 2, 3). 
# Mục tiêu: Trả lời 2 câu hỏi sống còn của doanh nghiệp:

# Nhân viên nào đạt KPI doanh số tổng?
# Tháng nào tình hình kinh doanh bị sụt giảm?

import numpy as np
import pandas as pd

# Danh sách nhân viên
staff = ['An', 'Bình', 'Chi', 'Dũng']
# Danh sách tháng
months = ['Jan', 'Feb', 'Mar']

# Ma trận doanh số (Đơn vị: Triệu VND)
# Hàng (Rows) = Nhân viên
# Cột (Cols) = Tháng [1, 2, 3]
sales_matrix = np.array([
    [150, 200, 180],  # An (Phong độ ổn định)
    [80,  90,  85],   # Bình (Hơi thấp)
    [300, 100, 50],   # Chi (Tháng 1 bán tốt, sau đó tụt dốc không phanh)
    [120, 130, 250]   # Dũng (Tăng trưởng mạnh)
])

print("Ma trận doanh số:\n", sales_matrix)


Ma trận doanh số:
 [[150 200 180]
 [ 80  90  85]
 [300 100  50]
 [120 130 250]]


In [ ]:

# 1. Tổng doanh số từng nhân viên -> Ép chiều ngang (Cột) -> Axis 1
print("-"*30)
s_staff_sales = sales_matrix.sum(axis=1)
s_staff_sales = pd.Series(data=s_staff_sales, index=staff)
print("\n--- Tổng doanh số nhân viên ---")
print(s_staff_sales)

# 2. Trung bình doanh số từng tháng -> Ép chiều dọc (Hàng) -> Axis 0
print("-"*30)
avg_sales_month = sales_matrix.mean(axis=0)
avg_sales_month = pd.Series(data = avg_sales_month, index=months)
print("\n--- Tổng doanh số tháng ---")
print(avg_sales_month)



------------------------------

--- Tổng doanh số nhân viên ---
An      530
Bình    255
Chi     450
Dũng    500
dtype: int64
------------------------------

--- Tổng doanh số tháng ---
Jan    162.50
Feb    130.00
Mar    141.25
dtype: float64


In [11]:
# Tìm những "Best Seller" (Nhân viên có tổng doanh số > 450 triệu).
best_seller = s_staff_sales[s_staff_sales >= 450]
print("\nBest Seller\n", best_seller)

# Tìm những "Tháng Báo Động" (Tháng có doanh số trung bình < 150 triệu).
sales_month_warning = avg_sales_month[avg_sales_month < 150]
print("\nTháng báo động\n",sales_month_warning)


Best Seller
 An      530
Chi     450
Dũng    500
dtype: int64

Tháng báo động
 Feb    130.00
Mar    141.25
dtype: float64


In [ ]:
# 3. Tính độ lệch chuẩn (Sự biến động doanh số)
# Axis = 1 vì xem sự biến động của từng ng qua các tháng
std_sales = sales_matrix.std(axis = 1)
s_std = pd.Series(data=std_sales, index=staff)

print("\n Độ lệch chuẩn (Sự bất thường)\n")
print(s_std)

# Tìm người có độ lệch chuẩn cao nhất (Thất thường nhất)
# Hàm idxmax() trả về Index (Tên) của giá trị lớn nhất
unstable_sale = s_std.idxmax()
print(f"\n Nhân viên phong độ thất thường nhất: {unstable_sale}")



 Độ lệch chuẩn (Sự bất thường)

An       20.548047
Bình      4.082483
Chi     108.012345
Dũng     59.066817
dtype: float64

 Sale có độ lệch chuẩn cao nhất: Chi
