In [4]:
import numpy as np

# Giả lập bảng điểm của 3 học viên (Hàng) với 4 môn học (Cột)
# Môn: [Python, SQL, Math, English]
diem_lms = np.array([
    [8, 9, 7, 6],   # Học viên A
    [5, 6, 5, 8],   # Học viên B
    [9, 10, 9, 9]   # Học viên C
])

print("Bảng điểm gốc:\n", diem_lms)
print("-" * 30)

# 1. Tổng hợp toàn bộ (Không quan tâm dòng cột)
print(f"Điểm cao nhất trường: {diem_lms.max()}")
print(f"Điểm trung bình toàn trường: {diem_lms.mean():.2f}")

# 2. Vận dụng AXIS (Quan trọng)
# Bài toán: Tính điểm trung bình của TỪNG HỌC VIÊN
# -> Ta cần tính theo chiều ngang (gom các môn lại) -> Axis 1
dtb_hoc_vien = diem_lms.mean(axis=1)
print(f"ĐTB từng học viên (A, B, C): {dtb_hoc_vien}")

# Bài toán: Tính điểm trung bình của TỪNG MÔN HỌC
# -> Ta cần tính theo chiều dọc (gom các học viên lại) -> Axis 0
dtb_mon_hoc = diem_lms.mean(axis=0)
print(f"ĐTB từng môn (Py, SQL, Math, Eng): {dtb_mon_hoc}")


cot_toan = diem_lms[:,2]
cot_toan_cong = cot_toan + 1.5
cot_toan_final = np.clip(cot_toan_cong, a_min=0, a_max=10)
diem_lms[:,2] = cot_toan_final
print(diem_lms)

Bảng điểm gốc:
 [[ 8  9  7  6]
 [ 5  6  5  8]
 [ 9 10  9  9]]
------------------------------
Điểm cao nhất trường: 10
Điểm trung bình toàn trường: 7.58
ĐTB từng học viên (A, B, C): [7.5  6.   9.25]
ĐTB từng môn (Py, SQL, Math, Eng): [7.33333333 8.33333333 7.         7.66666667]
[[ 8  9  8  6]
 [ 5  6  6  8]
 [ 9 10 10  9]]
