In [15]:
import numpy as np

# Tạo dữ liệu
# - np.array(): Chuyển list thường thành NumPy array.
# - np.arange(start, stop, step): Tạo dãy số (giống vòng lặp for i in range).
# - np.random: Tạo dữ liệu ngẫu nhiên (cực quan trọng để test khi chưa có data thật).

# 1. Chuyển đổi dữ liệu thô thành mảng để xử lý
raw_scores = [7.5, 8.0, 6.7, 9.1]
arr_scores = np.array(raw_scores)
print("Dữ liệu thô",arr_scores)

# 2. Tạo một cột số thứ tự (ID) cho 100 nhân viên
employee_id = np.arange(1,101)
print(employee_id)

# 3. Giả lập dữ liệu doanh thu của 5 cửa hàng trong 3 ngày (Ma trận 3x5)
# randint(low, high, size=(rows, cols))
sales_data = np.random.randint(100, 500, size=(3,5))
print(sales_data)



Dữ liệu thô [7.5 8.  6.7 9.1]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[[405 231 285 277 184]
 [128 423 208 273 440]
 [100 290 315 367 183]]


In [ ]:
# -- .shape -- 
# Kích thước mảng (dòng, cột). 
# Ví dụ: (1000, 5) nghĩa là bảng dữ liệu 1000 dòng, 5 cột.

In [ ]:
# -- .dtype -- 
# Kiểu dữ liệu. 
# Khác với Python list chấp nhận hỗn tạp, NumPy bắt buộc đồng nhất (vd: int32, float64).



In [ ]:
# -- .ndim ---
# Số chiều (1D = Vector, 2D = Matrix/Excel table, 3D = Image/Video data).