In [1]:
import pandas as pd
import numpy as np

# 1. Tạo dữ liệu giả (Thay vì dùng struct trong C hay Class trong Python App)
data = {
    'Ten_Hoc_Vien': ['An', 'Binh', 'Cuong', 'Dung', 'Em', 'Ha'],
    'Tuoi': [12, 13, 12, 14, 13, 12],
    'Diem_Python': [8.5, 9.0, np.nan, 7.5, 6.0, 9.5],  # np.nan là giả lập dữ liệu bị thiếu (ví dụ: vắng thi)
    'Diem_C': [7.0, 8.0, 6.5, np.nan, 9.0, 8.5],
    'Diem_D': [8.2, 9.5, 7.1, np.nan, 9.0, 8.5]
}

# 2. Chuyển dictionary thành DataFrame (Bảng dữ liệu)
# Đây là đối tượng quan trọng nhất bạn sẽ làm việc trong 100 ngày tới
df = pd.to_series = pd.DataFrame(data)

# 3. Xem dữ liệu
print("Dữ liệu thô:")
display(df) # Trong Jupyter, dùng display() sẽ đẹp hơn print()

# 4. Thử tính toán nhanh (Data Analysis cơ bản)
print("\n--- Thống kê nhanh ---")
print(f"Điểm Python trung bình: {df['Diem_Python'].mean()}")
print(f"Học viên lớn tuổi nhất: {df['Tuoi'].max()}")

Dữ liệu thô:


Ten_Hoc_Vien  Tuoi  Diem_Python  Diem_C  Diem_D
0           An    12          8.5     7.0     8.2
1         Binh    13          9.0     8.0     9.5
2        Cuong    12          NaN     6.5     7.1
3         Dung    14          7.5     NaN     NaN
4           Em    13          6.0     9.0     9.0
5           Ha    12          9.5     8.5     8.5


--- Thống kê nhanh ---
Điểm Python trung bình: 8.1
Học viên lớn tuổi nhất: 14


In [2]:
# Cell 2: Hỏi dữ liệu vài câu đơn giản

# Câu 1: Điểm Python trung bình của lớp là bao nhiêu?
avg_python = df['Diem_Python'].mean()

# Câu 2: Ai là người lớn tuổi nhất?
max_age = df['Tuoi'].max()

# Câu 3: Dữ liệu đang có vấn đề gì không? (Góc nhìn Senior)
missing_count = df['Diem_Python'].isnull().sum()

print(f"🔹 Điểm trung bình Python: {avg_python}")
print(f"🔹 Tuổi lớn nhất: {max_age}")
print(f"⚠️ Số bạn chưa có điểm Python (bị thiếu): {missing_count}")

🔹 Điểm trung bình Python: 8.1
🔹 Tuổi lớn nhất: 14
⚠️ Số bạn chưa có điểm Python (bị thiếu): 1


In [1]:
import numpy as np
import time

# --- PHẦN 1: TẠO MẢNG (ARRAY) ---
# List Python thông thường
python_list = [1, 2, 3, 4, 5]

# NumPy Array (Nhìn thì giống list, nhưng bản chất là C Array)
numpy_arr = np.array([1, 2, 3, 4, 5])

print(f"List thường: {python_list}")
print(f"NumPy Array: {numpy_arr}")
print("-" * 30)

# --- PHẦN 2: BROADCASTING (TÍNH TOÁN KHÔNG LOOP) ---
# Bài toán: Cộng thêm 10 vào tất cả phần tử

# Cách Python List (Phải dùng Loop hoặc Map)
# [x + 10 for x in python_list]

# Cách NumPy (Thẳng tay cộng như số học) -> ĐÂY LÀ VECTORIZATION
result = numpy_arr + 10 

print(f"Kết quả cộng 10: {result}")
print("-" * 30)

# --- PHẦN 3: THỬ THÁCH TỐC ĐỘ (BENCHMARK) ---
# Tạo 1 triệu phần tử ngẫu nhiên
size = 1_000_000
large_list = list(range(size))
large_array = np.array(range(size))

# Đo tốc độ List Python
start = time.time()
large_list_squared = [x**2 for x in large_list]
print(f"Python List tốn: {time.time() - start:.5f} giây")

# Đo tốc độ NumPy
start = time.time()
large_array_squared = large_array ** 2
print(f"NumPy Array tốn: {time.time() - start:.5f} giây")

List thường: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
------------------------------
Kết quả cộng 10: [11 12 13 14 15]
------------------------------
Python List tốn: 0.04076 giây
NumPy Array tốn: 0.00201 giây


In [4]:
# Giả lập điểm của 3 học viên (Hàng), mỗi người có 3 cột điểm
# Học viên A: 8, 9, 7
# Học viên B: 5, 6, 5
# Học viên C: 9, 10, 9
diem_tho = np.array([
    [8, 9, 7],
    [5, 6, 5],
    [9, 10, 9]
])

# Trọng số: Chuyên cần 10%, Giữa kỳ 30%, Cuối kỳ 60%
trong_so = np.array([0.1, 0.3, 0.6])

# TÍNH ĐIỂM TỔNG KẾT (Phép nhân ma trận - Dot Product)
# Thay vì viết 2 vòng lặp lồng nhau (Nested Loop), ta dùng np.dot
diem_tong_ket = diem_tho.dot(trong_so)
diem_tong_ket_lon_hon_8 = diem_tong_ket[diem_tong_ket >= 8]
diem_cao_nhat = diem_tong_ket.max()

print("Bảng điểm thô (Matrix):\n", diem_tho)
print("Trọng số:", trong_so)
print("-" * 20)
print("👉 Điểm tổng kết (Đã nhân trọng số):", diem_tong_ket)
print("👉 Điểm tổng kết lớn hơn 8:", diem_tong_ket_lon_hon_8)
print("👉 Điểm tổng kết Cao nhất:", diem_cao_nhat)

Bảng điểm thô (Matrix):
 [[ 8  9  7]
 [ 5  6  5]
 [ 9 10  9]]
Trọng số: [0.1 0.3 0.6]
--------------------
👉 Điểm tổng kết (Đã nhân trọng số): [7.7 5.3 9.3]
👉 Điểm tổng kết lớn hơn 8: [9.3]
👉 Điểm tổng kết Cao nhất: 9.299999999999999
